### ISSUE TITLE
Pharmacophore types

### ISSUE THREAD

**Issue by shkao** [biocheming/watvina#1]
Hi [biocheming](https://github.com/biocheming),

Thank you for developing watvina!
Just wondering, is it possible to set a "negatively charged group" pharmacophore type?

**Comment by biocheming** [comment]
> Hi [biocheming](https://github.com/biocheming),
> 
> Thank you for developing watvina! Just wondering, is it possible to set a "negatively charged group" pharmacophore type?

Good idea, I will try to set those kinds pharmacophore types.

**Comment by biocheming** [comment]
> Hi [biocheming](https://github.com/biocheming),
> 
> Thank you for developing watvina! Just wondering, is it possible to set a "negatively charged group" pharmacophore type?

Please check it now. if any bug, please report it. thank you.
