### ISSUE TITLE
请教一下关于极性氢和非极性氢的问题

### ISSUE THREAD

**Issue by sasaju** [biocheming/watvina#2]
我注意到您提到配体和受体必须保留极性氢和非极性氢，我发现部分Vina的教程也是这样写的。但是我发现有时候仅保留极性氢也能跑出结果，AutoDock Tools在ligand保存为pdbqt的时候默认也是去掉非极性氢。请问是否加极性氢的判断标准或者加上非极性氢目的是什么呢？

**Comment by biocheming** [comment]
Autodock Vina的原子类型里没有H的定义，极性氢仅仅是为了判断与其连接的原子是否是氢键供体。但是watvina定义了H的原子类型，不止2种，这些非极性氢对于准确预测构象有极大的意义，还有一些弱氢键也是“非极性氢”参与的，因此watvina需要保留所有的H，Autodock Vina只需要保留极性氢即可。
There's no hydrogen related atom types in Autodock Vina. Polar hydrogens are just for identify the hbond donor (bonded to HD). However, more than two different hydrogen atom types are defined in watvina, which are critical for conformation prediction properly. In addition, some non polar hydrogens are involved in the weak hbonds. So watvina needs all the hydrogens, while only polar hydrogens for Autodock vina.

**Comment by sasaju** [comment]
十分感谢，我明白了！
